name: sa_vertexai_gemini_lego
description: "lego is all you need"
#publish_to: 'none'
repository: https://github.com/flutter-lego/sa_vertexai_gemini_lego

version: 1.0.1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: #@add
  gap: #@add
  june_flow_util: #@add
  styled_widget: #@add
  modal_bottom_sheet: #@add
  flutter_zoom_drawer: #@add
  flutter_screenutil: #@add
  keyboard_attachable:
  firebase_core:
  firebase_vertexai:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  screenutil_lego: #@add
  widget_binding_lego: #@add
  firebase_vertexai_lego:
  firebase_core_lego:

flutter:
  assets:
    - assets/lego/firebase_vertexai_lego/
    - assets/lego/sa_vertexai_gemini_lego/
  uses-material-design: true

topics:
  - lego